apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-nucma
spec:
  displayName: NUCMA
  author:
    name: NUCMA
    website: https://nucma.cn
  description: 简约政府风格的 Halo 主题，适合校园官方站点使用
  logo: /themes/theme-nucma/assets/avatar-nucma.svg
  homepage: https://nucma.cn
  repo: https://github.com/chenhufei/theme-nucma
  issues: https://qm.qq.com/q/YEqkx4fa0M
  version: "3.21.0"
  requires: ">=2.0.0"
  settingName: theme-nucma-setting
  configMapName: theme-nucma-config
  license:
    - name: "MIT"
      url: "https://github.com/chenhufei/theme-nucma/blob/main/LICENSE"
  customTemplates:
    page:
      - name: page_about
        description: 关于页
        file: page_about.html