apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-nucma
spec:
  displayName: NUCMA
  author:
    name: NUCMA
    website: https://nucma.cn
  description: 面向全国高校自媒体联盟官网的 Halo 主题，聚焦公告公示、组织介绍与成员展示
  logo: "/themes/theme-nucma/assets/avatar-nucma.svg"
  homepage: "https://nucma.cn"
  repo: "https://github.com/chenhufei/theme-nucma"
  issues: "https://github.com/chenhufei/theme-nucma/issues"
  version: "1.0.4"
  requires: ">=2.0.0"
  settingName: theme-nucma-setting
  configMapName: theme-nucma-config
  customTemplates:
    category:
      - name: category
        description: 分类页
        file: categories.html
    page:
      - name: page
        description: 独立页面
        file: page.html
      - name: page_about
        description: 关于页
        file: page_about.html
